services:
  apprendreapi:
    image: apprendreapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
  postgres-test:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Adm1n
      POSTGRES_DB: apprendre_test
    ports:
      - 5432:5432

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5

